### PR TITLE
document-node-version

### LINKED ISSUE #7: Document minimum node version and consider increasing support
# To reproduce
On node 4.2.6
```
obehave --help
/usr/local/lib/node_modules/obehave/obehave.js:24
let port = options.port || process.env.OBEHAVE_PORT;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3
```

# Todo
* Document minimum node version
* See if we can increase support to earlier node versions

### PR DESCRIPTION
**Pull request by oh-wo**
Fixes #7 

# Done
 * Removed es6 variables
 * Set engines to 4.2.1 arbitrarily: https://docs.npmjs.com/files/package.json#engines
 * Set engineStrict true: https://docs.npmjs.com/files/package.json#enginestrict

# To test
`npm i -g git://github.com/Obehave-testing/cli.git#document-node-version`

# TODO
* Consider supporting only LTS

### CODE REVIEW

File: helpers.js [hunk 1]
```diff
@@ -9,4 +9,4 @@ function tryParseInt(arg) {
     return result;
 }
 
-module.exports = {tryParseInt}
\ No newline at end of file
+module.exports = {tryParseInt};
```
Comment (BevanR) [inline helpers.js:12]: 😢

**Review by BevanR — APPROVED** [review]

**Comment by oh-wo** [comment]
@mira-t hope this helps!
